[package]
name = "build-fs-tree"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"
build = false

[lib]
name = "build_fs_tree"
path = "lib.rs"
doc = true

[[bin]]
name = "build-fs-tree"
path = "_cli/build-fs-tree.rs"
doc = false

[dependencies]
derive_more = "^0.99.13"
pipe-trait = "^0.3.2"
serde_yaml = "^0.8.17"
structopt = "^0.3.21"
structopt-utilities = "^0.0.8"
text-block-macros = "^0.1.0"

[dependencies.serde]
version = "^1.0.125"
features = ["derive"]
