name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        timeout-minutes: 1
        continue-on-error: true
        if: matrix.os != 'macos-latest' # Cache causes errors on macOS
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-

      - name: Install Rust
        run: ./ci/github-actions/install-rust.sh

      - name: Fmt
        run: cargo fmt -- --check

      - name: Clippy
        env:
          FMT: 'false'
          LINT: 'true'
          DOC: 'false'
          BUILD: 'false'
          TEST: 'false'
        run: ./test.sh

      - name: Doc
        env:
          FMT: 'false'
          LINT: 'false'
          DOC: 'true'
          BUILD: 'false'
          TEST: 'false'
        run: ./test.sh

      - name: Test
        env:
          RUST_BACKTRACE: '1'
          FMT: 'false'
          LINT: 'false'
          DOC: 'false'
          BUILD: 'true'
          TEST: 'true'
          BUILD_FLAGS: '--locked'
          TEST_FLAGS: '--no-fail-fast'
        run: ./test.sh
