complete -c build-fs-tree -n "__fish_use_subcommand" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c build-fs-tree -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c build-fs-tree -n "__fish_use_subcommand" -f -a "create" -d 'Read YAML from stdin and create a new filesystem tree'
complete -c build-fs-tree -n "__fish_use_subcommand" -f -a "populate" -d 'Read YAML from stdin and populate an existing filesystem tree'
complete -c build-fs-tree -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c build-fs-tree -n "__fish_seen_subcommand_from create" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c build-fs-tree -n "__fish_seen_subcommand_from populate" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c build-fs-tree -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from populate; and not __fish_seen_subcommand_from help" -f -a "create" -d 'Read YAML from stdin and create a new filesystem tree'
complete -c build-fs-tree -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from populate; and not __fish_seen_subcommand_from help" -f -a "populate" -d 'Read YAML from stdin and populate an existing filesystem tree'
complete -c build-fs-tree -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from populate; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
